### ISSUE TITLE
[BUG REPORT] - clients.lua in fxmanifest file but there is no client.lua

### ISSUE THREAD

**Issue by instigate77** [Maximus7474/lb-tablet-dispatch-converter#8]
**Describe the bug**
clients.lua in fxmanifest file but there is no client.lua
**To Reproduce**
1. Start the script on a server
2.  Error is produced:

09:45:22 AM [    c-scripting-core] Creating script environments for lb-tablet-dispatch-converter
09:45:22 AM [resources:lb-tablet-] Warning: could not find client_script `client/*.lua` (defined in fxmanifest.lua:11)
09:45:22 AM [           resources] Started resource lb-tablet-dispatch-converter (1 warning)

**Expected behavior**
should not be included in fxmanifest.lua unless needed

**Screenshots**
09:45:22 AM [    c-scripting-core] Creating script environments for lb-tablet-dispatch-converter
09:45:22 AM [resources:lb-tablet-] Warning: could not find client_script `client/*.lua` (defined in fxmanifest.lua:11)
09:45:22 AM [           resources] Started resource lb-tablet-dispatch-converter (1 warning)

**Comment by Maximus7474** [comment]
Not really a bug, just a warning that can be ignored. I'm still working on the client conversions for some cases so I committed the entire fxmanifest  when saving the initial functional code.
If you really want to remove that warning just delete the reference in the fxmanifest, but either way doesn't change anything.

**Comment by instigate77** [comment]
Ok I know it's a warning but I thought maybe it would cause you some issues if people asked for help, is just mentioning it just in case....

By the way do you have a preview of the client for ps-dispatch?

**Comment by Maximus7474** [comment]
Not currently It's only really testing code and lots of comments, it's no where near being ready atm.
I'm very busy currently so I've halted all personal projects.

**Comment by instigate77** [comment]
ok thanks for the response cheers
